// app/components/FooterComponent.vue
<template>
  <footer class="ftr">
    <div class="ftr__container">
      <div class="ftr__in">
        <div class="ftr__brand-col">
          <NuxtLink to="/" class="ftr__brand">
            <ZIcon name="gem" class="ftr__logo" />
            <b>jouan.ovh</b>
          </NuxtLink>
          <p class="ftr__tagline">Développeur web freelance. Valognes, France.</p>
        </div>

        <nav class="ftr__col" aria-label="Navigation du pied de page">
          <h2 class="ftr__title">// Navigation</h2>
          <NuxtLink v-for="item in navItems" :key="item.to" :to="item.to" class="ftr__link">{{ item.label }}</NuxtLink>
        </nav>

        <div class="ftr__col">
          <h2 class="ftr__title">// Projets</h2>
          <a
            v-for="project in projects"
            :key="project.url"
            :href="project.url"
            target="_blank"
            rel="noopener noreferrer"
            class="ftr__link"
            >{{ project.name }}</a
          >
        </div>

        <div class="ftr__col">
          <h2 class="ftr__title">// Réseaux</h2>
          <LinkListComponent />
        </div>
      </div>

      <div class="ftr__bottom">
        <span>© {{ year }} Simon Jouan — jouan.ovh</span>
        <span class="ftr__term">anon.@jouan.ovh:~$ <span class="ftr__cmd">echo "merci de votre visite"</span></span>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import LinkListComponent from "~/components/LinkListComponent.vue";

const navItems = [
  { to: "/", label: "Accueil" },
  { to: "/services", label: "Services" },
  { to: "/about", label: "À propos" },
  { to: "/blog", label: "Blog" },
  { to: "/contact", label: "Contact" },
];

// Projets repris de data.js (UI kit).
const projects = [
  { name: "keova.app", url: "https://keova.app" },
  { name: "patio-conseil.fr", url: "https://patio-conseil.fr" },
];

const year = new Date().getFullYear();
</script>

<style lang="scss" scoped>
/* stylelint-disable selector-class-pattern -- convention DS BEM (block__element) portée depuis Footer.jsx/kit.css */
.ftr {
  margin-top: auto;
  background: var(--surface-1);
  border-top: 1px solid var(--border-subtle);
  padding: var(--space-12) 0 var(--space-8);
}

.ftr__container {
  width: 100%;
  max-width: var(--container-xl);
  margin: 0 auto;
  padding: 0 var(--space-6);
}

.ftr__in {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-8);
  align-items: flex-start;
  justify-content: space-between;
}

.ftr__brand-col {
  max-width: 300px;
}

.ftr__brand {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  margin-bottom: var(--space-3);
  text-decoration: none;

  .ftr__logo {
    font-size: 22px;
    color: var(--accent);
  }

  b {
    font-family: var(--font-mono);
    font-size: var(--fs-md);
    font-weight: var(--fw-bold);
    color: var(--text-strong);
  }
}

.ftr__tagline {
  margin: 0;
  font-size: var(--fs-sm);
  color: var(--text-muted);
}

.ftr__col {
  display: flex;
  flex-direction: column;
}

.ftr__title {
  margin: 0 0 var(--space-3);
  font-family: var(--font-mono);
  font-size: var(--fs-xs);
  font-weight: var(--fw-regular);
  letter-spacing: var(--ls-wider);
  text-transform: uppercase;
  color: var(--text-muted);
}

.ftr__link {
  display: block;
  padding: var(--space-1) 0;
  font-family: var(--font-mono);
  font-size: var(--fs-sm);
  color: var(--text-body);
  text-decoration: none;
  transition: color var(--dur-fast) var(--ease-standard);

  &:hover {
    color: var(--accent);
  }
}

.ftr__bottom {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-3);
  justify-content: space-between;
  margin-top: var(--space-8);
  padding-top: var(--space-5);
  font-family: var(--font-mono);
  font-size: var(--fs-xs);
  color: var(--text-faint);
  border-top: 1px solid var(--border-subtle);
}

.ftr__cmd {
  color: var(--term-green);
}

@media (prefers-reduced-motion: reduce) {
  .ftr__link {
    transition: none;
  }
}
</style>

// docs/design_system/ui_kits/jouan-site/Footer.jsx
function Footer({ go }) {
  const S = window.SITE;
  return (
    <footer className="ftr">
      <div className="container">
        <div className="ftr__in">
          <div className="ftr__col" style={{ maxWidth: "300px" }}>
            <div className="hdr__brand" style={{ marginBottom: "var(--space-3)" }}>
              <img src="../../assets/brand/logo-white.png" alt="" style={{ width: 22, height: 22 }} />
              <b style={{ fontFamily: "var(--font-mono)", color: "var(--text-strong)", fontSize: "var(--fs-md)", fontWeight: "var(--fw-bold)" }}>jouan.ovh</b>
            </div>
            <p className="prose" style={{ fontSize: "var(--fs-sm)", color: "var(--text-muted)", margin: 0 }}>
              {S.role}. {S.city}.
            </p>
          </div>
          <div className="ftr__col">
            <h4>// Navigation</h4>
            <a onClick={() => go("home")}>Accueil</a>
            <a onClick={() => go("services")}>Services</a>
            <a onClick={() => go("about")}>À propos</a>
            <a onClick={() => go("blog")}>Blog</a>
            <a onClick={() => go("contact")}>Contact</a>
          </div>
          <div className="ftr__col">
            <h4>// Projets</h4>
            {S.projects.map((p) => <a key={p.name} href={p.url} target="_blank" rel="noreferrer">{p.name}</a>)}
          </div>
          <div className="ftr__col">
            <h4>// Réseaux</h4>
            <div className="hexrow">
              {S.social.map((s) => {
                const Glyph = window.Icon[s.icon];
                return <a key={s.icon} className="hex" href={s.url} target="_blank" rel="noreferrer" title={s.label}><Glyph /></a>;
              })}
            </div>
          </div>
        </div>
        <div className="ftr__bottom">
          <span>© 2026 Simon Jouan — jouan.ovh</span>
          <span>anon.@jouan.ovh:~$ <span style={{ color: "var(--term-green)" }}>echo "merci de votre visite"</span></span>
        </div>
      </div>
    </footer>
  );
}
window.Footer = Footer;
